version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    env_file: .env
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file: .env
    depends_on:
      - mongodb
  api:
    restart: always
    build:
      context: https://github.com/Text-Analysis/doc-gost-api.git
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  web:
    restart: always
    build:
      context: https://github.com/Text-Analysis/doc-gost-web.git
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mongodb_data_container: