version: '3'

services:

  api:
    restart: always
    build:
      context: https://github.com/Text-Analysis/doc-gost-api.git
    env_file: .env
    ports:
      - "8000:8000"

  web:
    restart: always
    build:
      context: https://github.com/Text-Analysis/doc-gost-web.git
    ports:
      - "3000:3000"
